version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olawumi  # Set a non-empty password here
      POSTGRES_DB: Quickbite-projects
    ports:
      - "5433:5432"  # Map external port 5434 to internal port 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - Quickbite-network


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-crivii3v2p9s738pc1d0-a.oregon-postgres.render.com:5432/quickbite_lbxo
      SPRING_DATASOURCE_USERNAME: quickbite_lbxo_user
      SPRING_DATASOURCE_PASSWORD: e5Os5uK3Kr0ndmwa2ZIc1iv27cqgD2ss
    networks:
      - Quickbite-network

networks:
  Quickbite-network:
    driver: bridge

